### ISSUE TITLE
Worker Role != Webjob

### ISSUE THREAD

**Issue by snobu** [mspnp/performance-optimization#110]
In this document
https://github.com/mspnp/performance-optimization/blob/master/BusyFrontEnd/docs/BusyFrontEnd.md

>Using a worker role is simply one solution. If you are using Azure Websites, you can use other options  such as WebJobs.

__Webjobs__ are running inside the same instance as the Azure Website, so it's not going to have a decoupling effect. That's what's i've seen in production.  Sure you may scale out to let's say 10 instances (so, 10 x Webjobs) but i feel like this has the same effect as just doing 10 x WebRole.

(The Hanselman):
http://www.hanselman.com/blog/IntroducingWindowsAzureWebJobs.aspx

>WebJobs aims to make developing, running, and scaling this easier. They are built into Azure Websites and run in the same VM as your Web Sites.

**Comment by dragon119** [comment]
By default, WebJobs scale with the website. However, jobs can be configured to run on single instance by setting the is_singleton configuration property to true. Single instance WebJobs are useful for tasks that you do not want to scale or run as simultaneous multiple instances, such as re-indexing, data analysis, and similar tasks.
To minimize the impact of jobs on the performance of the website, consider creating an empty Azure Web Sites instance in a new App Service Plan to host WebJobs that may be long running or resource intensive.
This guidance has a lot more about background jobs.
https://github.com/mspnp/azure-guidance/blob/master/Background-Jobs.md

**Comment by astaykov** [comment]
@snobu you say:
>Webjobs are running inside the same instance as the Azure Website, so it's not going to have a decoupling effect. 

No one would stop you from having a "dedicated website" just to run your jobs there. Thus bringing you the full decoupling you need.  And the effect is not like doing 10x Worker Role, because the programming model for Web Jobs is way more simplified (which has its downsides, too). But if you can fit your background worker into a Web Job, you can safely dedicate a website for that web job to make sure that it "runs alone", independently of your other application modules.

**Comment by snobu** [comment]
Ha. It never crossed my mind that running a Website exclusively for Webjobs can be very similar to a reduced complexity Worker Role. This might come in handy in many scenarios where a Worker Role is probably just too much "fat" for simple tasks, but was designed that way so resource contention is minimum to none.

Thank you both.
