### ISSUE TITLE
Maybe recommend a Queue

### ISSUE THREAD

**Issue by snobu** [mspnp/performance-optimization#111]
Let me just start by saying that i admire the work you guys put into these performance optimization documents and that the level of detail and attention is probably unprecedented.

If i may, i'd like to bring this to your attention:
In the Chatty IO document here https://github.com/mspnp/performance-optimization/blob/master/ChattyIO/docs/ChattyIO.md, after recommending buffering data into memory

>You should consider the following points:
>
> * [...]
> * [...]
> * Data buffered in memory to optimize write requests is vulnerable if the application crashes and may be lost.

the reader might feel that he or she just traded performance for risk and is probably a bit dissapointed. Which is a fair trade in most situations. But, am i completely wrong in saying this is one scenario in which a Queue would make sense, thus alleviating much of the risk of data loss given its durable nature?

**Comment by bennage** [comment]
We updated the guidance. Thanks for your recommendation.
