### ISSUE TITLE
HttpClient usage: MSDN vs the ImproperInstantiation article

### ISSUE THREAD

**Issue by jjanuszkiewicz** [mspnp/performance-optimization#122]
The [ImproperInstantiation](https://github.com/mspnp/performance-optimization/blob/master/ImproperInstantiation/docs/ImproperInstantiation.md) article makes a recommendation to reuse a single `HttpClient` instance for handling multiple requests.

The article even has this note:

> **Note:** The key element of this anti-pattern is that an application repeatedly creates and destroys instances of a shareable object. If a class is not shareable (if it is not thread-safe), then this anti-pattern does not apply.

But the [documentation](https://msdn.microsoft.com/en-us/library/system.net.http.httpclient.aspx) of `HttpClient` says:

> Any public **static** (**Shared** in Visual Basic) members of this type are thread safe. Any instance members are not guaranteed to be thread safe.

Is this an error in the `HttpClient` docs, or is the ImproperInstantiation article wrong?

**Comment by MikeWasson** [comment]
The note is saying that this particular guidance only applies to objects that can be shared. In other words, if an object is *not* thread-safe, then of course it shouldn't be used as a singleton.

But `HttpClient` *is* thread-safe (and designed to be shared).

**Comment by jjanuszkiewicz** [comment]
It's understood that this applies only to shareable objects. It's just not clear where the claim that `HttpClient` is thread-safe comes from - the documentation states the opposite. If the class documentation is wrong, can you please advise what can be done to get it fixed?

I have more concerns related to having a long-lived `HttpClient` instance - it is a functional (possibly breaking) change, because:
- [it won't react to DNS changes](http://byterot.blogspot.co.uk/2016/07/singleton-httpclient-dns.html) and requires non-obvious hacks to work around, which still don't cover all edge cases,
- according to [this comment](http://aspnetmonsters.com/2016/08/2016-08-27-httpclientwrong/#comment-2879330524), it will break load-balanced scenarios (I haven't verified this myself yet).

Can you please comment on these?

**Comment by MikeWasson** [comment]
I see - regarding thread safety, the [latest API doc](https://msdn.microsoft.com/en-us/library/system.net.http.httpclient(v=vs.110).aspx) clarifies which methods are thread safe. (See the Remarks section.)

**Comment by jjanuszkiewicz** [comment]
Oh, I see. It doesn't help that the old API doc is the #1 search result when searching for "HttpClient Class" in Google.
