### ISSUE TITLE
Suggestion for alternative / functional option

### ISSUE THREAD

**Issue by solvingj** [mspnp/performance-optimization#126]
These single instances are very broadly useful objects that people will want to be able to use in very simple contexts.  Azure function promotes and encourages smaller/simpler functions for simple use cases.  In such contexts, the "try with resources + a lambda" style can give developers access to the instance and the freedom to use it however they want at the callsite, without having to wrap all their various HTTP requests in separate class methods, and go deep into abstractions with lots of boilerplate. 

Again, it's an alternative style that makes it easier to use HttpClient in a healthy way for simple functions. 

Here's an example for HttpClient

 ```csharp
   public class SingleHttpClient
    {
        private static readonly HttpClient HttpClient;

        static SingleHttpClient()
        {
            HttpClient = new HttpClient();
        }

        public void DoWithClient<T>(Action<HttpClient> action)
        {
            action(HttpClient);
        }

        public async Task DoWithClient(Action<HttpClient> action)
        {
            await Task.Run(() => action(HttpClient));
        }

        public T DoWithClient<T>(Func<HttpClient, T> func)
        {
            return func(HttpClient);
        }

        public async Task<T> DoWithClient<T>(Func<HttpClient, Task<T>> func)
        {
            return await func(HttpClient);
        }
    }
```

And then to use., something like this... 

```csharp
        HttpResponseMessage response = await new SingleHttpClient()
                .DoWithClient(async (client) => await client.GetAsync("http://somehost:8080/api/"));
```

And, because this is a composeable style, you could write a DocumentClient using the same strategy, which calls upon this SingleHttpClient class just like the user would. 

Just a thought, thanks for the great content here.

**Comment by solvingj** [comment]
I guess this doesn't provide any additional value compared to just allowing the caller to "get" a handle to the client and then use it normally.  I was actually trying to provide a trimmed down version of what I actually do, which is to use a functional library here:

https://github.com/vkhorikov/CSharpFunctionalExtensions

But it turns out that the benefits of using the functional style depend on a lot of things like the Result container and the "bind" methods of "OnSuccess" and "OnFailure".

**Comment by MikeWasson** [comment]
Thanks - it's an interesting pattern. Since the main focus of this guidance is how to analyze the perf issues, we've intentionally kept the code as straight-forward as possible.
