### ISSUE TITLE
Broken link to detailed documentation

### ISSUE THREAD

**Issue by SvenAelterman** [mspnp/performance-optimization#128]
The readme.md for Improper Instantiation (https://github.com/mspnp/performance-optimization/tree/master/ImproperInstantiation) contains a broken link to "Detailed Documentation," which points to https://github.com/mspnp/performance-optimization/blob/master/ImproperInstantiation/docs/ImproperInstantiation.md.

That file does not exist.

**Comment by ckittel** [comment]
Thanks for noticing this @SvenAelterman.  I'm afraid we don't have any specific docs, even in draft form, that I could find.  So for now, we'll remove that link as to not cause confusion.
