### ISSUE TITLE
"unnecessary rows" controller is not comparing similar queries

### ISSUE THREAD

**Issue by bennage** [mspnp/performance-optimization#76]
In [UnnecessaryRowsController](https://github.com/mspnp/performance-optimization/blob/master/ExtraneousFetching/ExtraneousFetching.WebApi/Controllers/UnnecessaryRowsController.cs),

```
                var salesPersons = await context.SalesPersons
                    .Include(sp => sp.SalesOrderHeaders) // This include forces eager loading.
                    .ToListAsync();
``` 
should match
```
                var query = from sp in context.SalesPersons
                            from soh in sp.SalesOrderHeaders
                            select soh.TotalDue;
```

**Comment by mj1856** [comment]
The code has been updated and tests have been re-ran.  The documentation still needs to be updated to reflect the changes.  @JohnPWSharp - Please update the docs.  Thanks!

**Comment by bennage** [comment]
Did I close this by merging the pr? :confused:

**Comment by mj1856** [comment]
Yes, since I said "fixes" with the issue number.

Reopening until docs are updated.

**Comment by bennage** [comment]
The doc looks updated to me.
